language: c
install: sudo make install
script: make tests && ./curryTest && ./pipeTest && ./threading-pipes-test
compiler: clang
include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
